config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :rooms do
    resources :messages 
  end
  
 
  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
 

  resources :users
  get "signup" => "users#new"

  #get 'user/:id', to: 'users#show', as: 'user' possibly use slugs instead

  

 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  before_create :confirm_participant

  belongs_to :user
  belongs_to :room
  
  after_create_commit { broadcast_append_to room }
  

  def confirm_participant
    return unless room.is_private

    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :participants, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  scope :public_rooms, -> { where(is_private: false) }

  after_create_commit {broadcast_if_public}

  def broadcast_if_public
    broadcast_append_to "rooms" unless self.is_private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, is_private: true)
    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id )
    end
    single_room
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :messages 

  validates :name, presence: true

  validates :email, presence: true,
                    format: { with: /\S+@\S+/ },
                    uniqueness: { case_sensitive: false }
                    

  validates :password, length: { minimum: 10, allow_blank: true }

  validates :username, presence: true,
                     format: { with: /\A[A-Z0-9]+\z/i },
                     uniqueness: { case_sensitive: false }

  
scope :by_name, -> { order(:name) }
scope :all_except, ->(user) { where.not(id: user) }
scope :not_admins, -> { by_name.where(admin: false) }

after_create_commit { broadcast_append_to "users" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private



  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

   helper_method :current_user


  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end

  def require_admin
    unless current_user_admin?
      redirect_to root_url, alert: "Unauthorized access!"
    end
  end

  def current_user_admin?
    current_user && current_user(&:admin)
  end
  
  helper_method :current_user_admin?

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  

  def create
    @current_user = current_user
    @message = @current_user.messages.create(content: msg_params[:content], room_id: params[:room_id])
  end

  private

  def msg_params
    params.require(:message).permit(:content)
  end

  


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
    render 'index'
  end

  def show
    @single_room = Room.find(params[:id])

    @room = Room.new
    @rooms = Room.public_rooms

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    @users = User.all_except(current_user)
    render 'index'
  end

  

  def create
    @room = Room.create(name: params["room"]["name"])
  end

  def update

  end

  def destroy

  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email_or_username]) ||
           User.find_by(username: params[:email_or_username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, 
                  notice: "Welcome back, #{user.name}!"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil 
    redirect_to root_path, notice: "You are now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :require_signin, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  # def index
  #   @users = User.not_admins
  # end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @rooms = Room.public_rooms
    @users = User.all_except(@current_user)
    @room = Room.new
    @message = Message.new
    @room_name = get_name(@user, @current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, @current_user], @room_name)
    @messages = @single_room.messages

    render "rooms/index"
  end

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end


  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil 
    redirect_to root_path, alert: "Account successfully deleted!"
  end
  
  private

  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end

  def require_correct_user
    @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
  end
  
  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
    <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex',
  data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CupToCup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  
    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>
  </head>

  <body>
    <%# <%= render "layouts/header" %> 

    <div class="content">
      <%= render "layouts/flash" %>
     <%= yield %>
    </div>

  <%# <%= render "layouts/footer" %> 
    
  </body>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%= message.user.id %>">
  <div class="message-box msg-<%= message.user.id %> " >
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.username %> </h6>
    <% end %>
  <%= message.content %>
  </div>
</div>

app/views/pages/home.html.erb
<h1> Cup to Cup Chat Demo </h1>

<% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Settings", edit_user_path(current_user) %>
        </li>
        <li>
        <%# <%= button_to "Sign Out", session_path, method: :delete,
                                class: "button" %> 
        <%= link_to "Sign Out", session_path,
                 data: { turbo_method: :delete },
                 class: "button" %>
        </li>
        <li>
         <%= link_to "Start Chatting", rooms_path %>
         </li>
      <% else %>
        <li>
          <%= link_to "Sign In", signin_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
<% end %>

app/views/rooms/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/rooms/_room.html.erb
<div> <%= link_to room.name, room %> </div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="row  text-light">
  <div id="side_panel" class="col-md-4 col-sm-4">
    <h5> <%= current_user.username %> </h5>
    <h4> Users </h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>
    <h4> Rooms </h4>
    <%= turbo_stream_from "rooms" %>
    <%= render 'rooms/new_room_form' %>
    <div id="rooms">
      <%= render @rooms%>
    </div>
  </div>
  <div id="room_container"
  class="col-md-8 col-sm-8 text-light">
    <% if @single_room %>
      <div id="single_room">
        <h4 class="text-center"> <%= @user&.username || @single_room.name %> </h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages">
          <%= render @messages %>
        </div>
        <%= render 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :username %>
  <%= f.text_field :username, size: 4, maxlength: 10,  placeholder: "Alphanumeric characters only!"%>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Update Account" %>
  <% end %>
<% end %>

app/views/users/_user.html.erb
<div> <%= link_to user.username, user %> </div>

app/views/users/edit.html.erb
<h1> Edit Account </h1>
<%= render "form", user: @user %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>